///
/// File generated by cpct_aks2c CPCtelera script
/// Souce file of this conversion: src/assets/music/ingame.aks
/// Generation time: lun 02 nov 2020 17:48:16 CET
///

/// Song 'song_ingame' metadata macros
#define song_ingame_address  0x3C00
#define song_ingame_size     132
#define song_ingame_end      0x3c83

/// Song 'song_ingame' array declaration
extern void song_ingame[song_ingame_size];
