///
/// File generated by cpct_aks2c CPCtelera script
/// Souce file of this conversion: src/assets/music/intro.aks
/// Generation time: mar 03 nov 2020 07:58:36 CET
///

/// Song 'song_intro' metadata macros
#define song_intro_address  0x3C83
#define song_intro_size     169
#define song_intro_end      0x3d2b

/// Song 'song_intro' array declaration
extern void song_intro[song_intro_size];
